name: platformer101
description: Simple Platformer Game
version: 0.0.0
publish_to: none

environment:
  sdk: ^2.19.1
  flutter: ^3.7.1

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.6.0
  flame_tiled: ^1.9.1

flutter:
  assets:
    - assets/images/
    - assets/tiles/